<?php

namespace App\Enums;

enum CountryCode: string
{
    case AD = 'AD';
    case AE = 'AE';
    case AF = 'AF';
    case AG = 'AG';
    case AL = 'AL';
    case AM = 'AM';
    case AN = 'AN';
    case AO = 'AO';
    case AQ = 'AQ';
    case AR = 'AR';
    case AT = 'AT';
    case AU = 'AU';
    case AW = 'AW';
    case AZ = 'AZ';
    case BA = 'BA';
    case BD = 'BD';
    case BE = 'BE';
    case BF = 'BF';
    case BG = 'BG';
    case BH = 'BH';
    case BJ = 'BJ';
    case BO = 'BO';
    case BR = 'BR';
    case BS = 'BS';
    case BW = 'BW';
    case BY = 'BY';
    case BZ = 'BZ';
    case CA = 'CA';
    case CD = 'CD';
    case CG = 'CG';
    case CH = 'CH';
    case CI = 'CI';
    case CL = 'CL';
    case CM = 'CM';
    case CN = 'CN';
    case CO = 'CO';
    case CR = 'CR';
    case CW = 'CW';
    case CY = 'CY';
    case CZ = 'CZ';
    case DE = 'DE';
    case DK = 'DK';
    case DO = 'DO';
    case DZ = 'DZ';
    case EC = 'EC';
    case EE = 'EE';
    case EG = 'EG';
    case ES = 'ES';
    case ET = 'ET';
    case FI = 'FI';
    case FJ = 'FJ';
    case FO = 'FO';
    case FR = 'FR';
    case GA = 'GA';
    case GB = 'GB';
    case GE = 'GE';
    case GH = 'GH';
    case GN = 'GN';
    case GP = 'GP';
    case GR = 'GR';
    case GT = 'GT';
    case GU = 'GU';
    case GY = 'GY';
    case HK = 'HK';
    case HN = 'HN';
    case HR = 'HR';
    case HU = 'HU';
    case ID = 'ID';
    case IE = 'IE';
    case IL = 'IL';
    case IN = 'IN';
    case IQ = 'IQ';
    case IR = 'IR';
    case IS = 'IS';
    case IT = 'IT';
    case JM = 'JM';
    case JO = 'JO';
    case JP = 'JP';
    case KE = 'KE';
    case KG = 'KG';
    case KH = 'KH';
    case KN = 'KN';
    case KR = 'KR';
    case KW = 'KW';
    case KZ = 'KZ';
    case LA = 'LA';
    case LB = 'LB';
    case LC = 'LC';
    case LK = 'LK';
    case LT = 'LT';
    case LU = 'LU';
    case LV = 'LV';
    case MA = 'MA';
    case MC = 'MC';
    case MD = 'MD';
    case ME = 'ME';
    case MG = 'MG';
    case MK = 'MK';
    case ML = 'ML';
    case MM = 'MM';
    case MN = 'MN';
    case MO = 'MO';
    case MT = 'MT';
    case MU = 'MU';
    case MV = 'MV';
    case MX = 'MX';
    case MY = 'MY';
    case MZ = 'MZ';
    case NA = 'NA';
    case NE = 'NE';
    case NG = 'NG';
    case NI = 'NI';
    case NL = 'NL';
    case NO = 'NO';
    case NP = 'NP';
    case NZ = 'NZ';
    case OM = 'OM';
    case PA = 'PA';
    case PE = 'PE';
    case PG = 'PG';
    case PH = 'PH';
    case PK = 'PK';
    case PL = 'PL';
    case PR = 'PR';
    case PS = 'PS';
    case PT = 'PT';
    case PY = 'PY';
    case QA = 'QA';
    case RO = 'RO';
    case RS = 'RS';
    case RU = 'RU';
    case RW = 'RW';
    case SA = 'SA';
    case SE = 'SE';
    case SG = 'SG';
    case SI = 'SI';
    case SK = 'SK';
    case SN = 'SN';
    case SUHH = 'SUHH';
    case SV = 'SV';
    case SY = 'SY';
    case TG = 'TG';
    case TH = 'TH';
    case TJ = 'TJ';
    case TN = 'TN';
    case TR = 'TR';
    case TT = 'TT';
    case TW = 'TW';
    case TZ = 'TZ';
    case UA = 'UA';
    case UG = 'UG';
    case US = 'US';
    case UY = 'UY';
    case UZ = 'UZ';
    case VE = 'VE';
    case VN = 'VN';
    case XAS = 'XAS';
    case XWG = 'XWG';
    case XWW = 'XWW';
    case ZA = 'ZA';
    case ZM = 'ZM';
    case ZW = 'ZW';

    /**
     * @var array<string, string>
     */
    private const LABELS = [
        'AD' => 'Andorra',
        'AE' => 'United Arab Emirates',
        'AF' => 'Afghanistan',
        'AG' => 'Antigua and Barbuda',
        'AL' => 'Albania',
        'AM' => 'Armenia',
        'AN' => 'Netherlands Antilles',
        'AO' => 'Angola',
        'AQ' => 'Antarctica',
        'AR' => 'Argentina',
        'AT' => 'Austria',
        'AU' => 'Australia',
        'AW' => 'Aruba',
        'AZ' => 'Azerbaijan',
        'BA' => 'Bosnia and Herzegovina',
        'BD' => 'Bangladesh',
        'BE' => 'Belgium',
        'BF' => 'Burkina Faso',
        'BG' => 'Bulgaria',
        'BH' => 'Bahrain',
        'BJ' => 'Benin',
        'BO' => 'Bolivia',
        'BR' => 'Brazil',
        'BS' => 'Bahamas',
        'BW' => 'Botswana',
        'BY' => 'Belarus',
        'BZ' => 'Belize',
        'CA' => 'Canada',
        'CD' => 'Democratic Republic of the Congo',
        'CG' => 'Congo',
        'CH' => 'Switzerland',
        'CI' => "Cote d'Ivoire",
        'CL' => 'Chile',
        'CM' => 'Cameroon',
        'CN' => 'China',
        'CO' => 'Colombia',
        'CR' => 'Costa Rica',
        'CW' => 'Curacao',
        'CY' => 'Cyprus',
        'CZ' => 'Czechia',
        'DE' => 'Germany',
        'DK' => 'Denmark',
        'DO' => 'Dominican Republic',
        'DZ' => 'Algeria',
        'EC' => 'Ecuador',
        'EE' => 'Estonia',
        'EG' => 'Egypt',
        'ES' => 'Spain',
        'ET' => 'Ethiopia',
        'FI' => 'Finland',
        'FJ' => 'Fiji',
        'FO' => 'Faroe Islands',
        'FR' => 'France',
        'GA' => 'Gabon',
        'GB' => 'United Kingdom',
        'GE' => 'Georgia',
        'GH' => 'Ghana',
        'GN' => 'Guinea',
        'GP' => 'Guadeloupe',
        'GR' => 'Greece',
        'GT' => 'Guatemala',
        'GU' => 'Guam',
        'GY' => 'Guyana',
        'HK' => 'Hong Kong',
        'HN' => 'Honduras',
        'HR' => 'Croatia',
        'HU' => 'Hungary',
        'ID' => 'Indonesia',
        'IE' => 'Ireland',
        'IL' => 'Israel',
        'IN' => 'India',
        'IQ' => 'Iraq',
        'IR' => 'Iran',
        'IS' => 'Iceland',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JO' => 'Jordan',
        'JP' => 'Japan',
        'KE' => 'Kenya',
        'KG' => 'Kyrgyzstan',
        'KH' => 'Cambodia',
        'KN' => 'Saint Kitts and Nevis',
        'KR' => 'South Korea',
        'KW' => 'Kuwait',
        'KZ' => 'Kazakhstan',
        'LA' => 'Laos',
        'LB' => 'Lebanon',
        'LC' => 'Saint Lucia',
        'LK' => 'Sri Lanka',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'LV' => 'Latvia',
        'MA' => 'Morocco',
        'MC' => 'Monaco',
        'MD' => 'Moldova',
        'ME' => 'Montenegro',
        'MG' => 'Madagascar',
        'MK' => 'North Macedonia',
        'ML' => 'Mali',
        'MM' => 'Myanmar',
        'MN' => 'Mongolia',
        'MO' => 'Macau',
        'MT' => 'Malta',
        'MU' => 'Mauritius',
        'MV' => 'Maldives',
        'MX' => 'Mexico',
        'MY' => 'Malaysia',
        'MZ' => 'Mozambique',
        'NA' => 'Namibia',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NI' => 'Nicaragua',
        'NL' => 'Netherlands',
        'NO' => 'Norway',
        'NP' => 'Nepal',
        'NZ' => 'New Zealand',
        'OM' => 'Oman',
        'PA' => 'Panama',
        'PE' => 'Peru',
        'PG' => 'Papua New Guinea',
        'PH' => 'Philippines',
        'PK' => 'Pakistan',
        'PL' => 'Poland',
        'PR' => 'Puerto Rico',
        'PS' => 'Palestine',
        'PT' => 'Portugal',
        'PY' => 'Paraguay',
        'QA' => 'Qatar',
        'RO' => 'Romania',
        'RS' => 'Serbia',
        'RU' => 'Russia',
        'RW' => 'Rwanda',
        'SA' => 'Saudi Arabia',
        'SE' => 'Sweden',
        'SG' => 'Singapore',
        'SI' => 'Slovenia',
        'SK' => 'Slovakia',
        'SN' => 'Senegal',
        'SUHH' => 'Soviet Union',
        'SV' => 'El Salvador',
        'SY' => 'Syria',
        'TG' => 'Togo',
        'TH' => 'Thailand',
        'TJ' => 'Tajikistan',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TT' => 'Trinidad and Tobago',
        'TW' => 'Taiwan',
        'TZ' => 'Tanzania',
        'UA' => 'Ukraine',
        'UG' => 'Uganda',
        'US' => 'United States',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VE' => 'Venezuela',
        'VN' => 'Vietnam',
        'XAS' => 'Asia',
        'XWG' => 'West Germany',
        'XWW' => 'Worldwide',
        'ZA' => 'South Africa',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ];

    public function label(): string
    {
        return self::LABELS[$this->value];
    }

    public static function labelFor(?string $code): ?string
    {
        if (! filled($code)) {
            return null;
        }

        return self::tryFrom(strtoupper((string) $code))?->label();
    }
}
